FROM node:18

ARG MONGO_URI
ARG MONGODB_NAME
ARG JWT_SECRET
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
ARG EMAIL_REPLY_TO
ARG EMAIL_FROM
ARG SPHERE_ACCOUNT_ID
ARG SPHERE_PROBLEM_API_KEY
ARG SPHERE_COMPILERS_API_KEY

ENV MONGO_URI=$MONGO_URI
ENV MONGODB_NAME=$MONGODB_NAME
ENV JWT_SECRET=$JWT_SECRET
ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ENV EMAIL_REPLY_TO=$EMAIL_REPLY_TO
ENV EMAIL_FROM=$EMAIL_FROM
ENV SPHERE_ACCOUNT_ID=$SPHERE_ACCOUNT_ID
ENV SPHERE_PROBLEM_API_KEY=$SPHERE_PROBLEM_API_KEY
ENV SPHERE_COMPILERS_API_KEY=$SPHERE_COMPILERS_API_KEY
ENV PORT=8080

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

RUN npm run build

CMD [ "npm", "run", "start" ]
